services:
  app:
    build: .
    volumes:
      - app-static-files:/var/data/app/static
      - app-media-files:/var/data/app/media
      - app-db-files:/var/data/app/db
    environment:
      DJANGO_DEBUG: 'false'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'app-db'
      DJANGO_ALLOWED_HOSTS: '*'
    profiles:
      - all


  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/keys/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx/keys/server.key:/etc/ssl/private/server.key:ro
      - ./nginx/keys/server.crt:/etc/ssl/certs/server.crt:ro
      - app-static-files:/app/static:ro
      - app-media-files:/app/media:ro
    depends_on:
      - app
    profiles:
      - all
  postgres:
      image: postgres
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak-26-0-7:
      image: quay.io/keycloak/keycloak:26.0.7
      environment:
      
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_ADMIN_USERNAME: admin
        KC_ADMIN_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      command: start-dev
      ports:
        - 8080:8080
      depends_on:
        - postgres
      volumes:
        - ./keycloak/keycloak-themes/custom:/opt/keycloak/themes/custom
volumes:
  app-static-files:
  app-media-files:
  app-db-files:
  postgres-data:
