services:
  app:
    build: .
    volumes:
      - app-static-files:/var/data/app/static
      - app-media-files:/var/data/app/media
      - app-db-files:/var/data/app/db
    environment:
      DJANGO_DEBUG: 'false'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'app-db'
      DJANGO_ALLOWED_HOSTS: '*'
    profiles:
      - all


  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/keys/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx/keys/server.key:/etc/ssl/private/server.key:ro
      - ./nginx/keys/server.crt:/etc/ssl/certs/server.crt:ro
      - app-static-files:/app/static:ro
      - app-media-files:/app/media:ro
    depends_on:
      - app
    profiles:
      - all

volumes:
  app-static-files:
  app-media-files:
  app-db-files:
  postgres-data: