# Generated by Django 4.2.16 on 2024-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(auto_created=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
